# platform :ios, '14.0'
# require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# target 'PocketVax' do
#   # Pods for PocketVax
#   pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
#   pod 'FBReactNativeSpec', :path => "../node_modules/react-native/React/FBReactNativeSpec"
#   pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
#   pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
#   pod 'React', :path => '../node_modules/react-native/'
#   pod 'React-Core', :path => '../node_modules/react-native/'
#   pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
#   pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
#   pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
#   pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
#   pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
#   pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
#   pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
#   pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
#   pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
#   pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
#   pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
#   pod 'React-perflogger', :path => '../node_modules/react-native/ReactCommon/reactperflogger'
#   pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

#   pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
#   pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
#   pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
#   pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
#   pod 'React-callinvoker', :path => "../node_modules/react-native/ReactCommon/callinvoker"
#   pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
#   pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

#   pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
#   pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
#   pod 'RCT-Folly', :podspec => '../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec'

#   pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

#   pod 'RNDateTimePicker', :path => '../node_modules/@react-native-community/datetimepicker'

#   pod 'RNReactNativePdfLib', :path => '../node_modules/react-native-pdf-lib'

#   pod 'react-native-html-to-pdf', :path => '../node_modules/react-native-html-to-pdf'

#   use_native_modules!
#   pod 'react-native-appearance', :path => '../node_modules/react-native-appearance'

# end


# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip
platform :ios, '12.4'
prepare_react_native_project!
# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled
linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end
target 'PocketVax' do
  config = use_native_modules!
  # Flags change depending on the env values.
  flags = get_default_flags()
  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  # target 'PocketVax' do
  #   inherit! :complete
  #   # Pods for testing
  # end
  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.4'
      end
    end
  end
end